main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.homepage, name="homepage"),
    path("<eng_name>/services/", views.services, name='services'),
]

services/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("services/", views.services, name='services'),
    path("order_search/", views.orderSearch, name='order_search'),
    path("render_document/", views.renderDocument, name='render_document')
]

tiancigong/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
#from django.conf.urls.static import static

urlpatterns = [
    path("", include('main.urls')),
    path("", include('users.urls')),
    path("", include('services.urls')),
    path('admin/', admin.site.urls)
]

#if settings.DEBUG:
#    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

services/models.py
from django.db import models
from django.utils import timezone

class Orders(models.Model):
    order_choices = (
        ('补运', '补运'),
        ('补财库', '补财库'),
        ('拜孔子', '拜孔子'),
        ('安太岁', '安太岁'),
        ('接财神', '接财神'),
        ('拜天狗', '拜天狗'),
        ('拜無鬼', '拜無鬼'),
        ('拜天宫', '拜天宫')
    )
    progress = (
        ("In Progress","In Progress"),
        ("Completed","Completed")
    )
    account = models.ForeignKey('users.AccountUser', on_delete=models.CASCADE)
    member = models.ManyToManyField('users.Member')
    order_type = models.CharField(max_length=255, choices=order_choices)
    status = models.CharField(max_length=50, choices=progress, default="In Progress")
    order_number = models.CharField(max_length=12, unique=True)
    created_date = models.DateTimeField(default=timezone.now)
    
    def get_order_choices(self):
        return self.order_choices
        
    def get_progress(self):
        return self.progress
    
    def __str__(self):
        return self.order_type
       

services/forms.py
from django import forms
from django.forms import ModelForm
from .models import Orders
from users.models import Member, AccountUser
from users.utilities import generate_membership

class OrderForm(ModelForm):
    member_id = forms.CharField(max_length=36)
    member_name = forms.MultipleChoiceField(choices=(),required=True)
    
    def __init__(self, request, *args, **kwargs):
        super(OrderForm, self).__init__(*args, **kwargs)
        members = Member.objects.filter(account=request.user)
        mem = []
        for member in members:
            mem.append((getattr(member, 'name'),getattr(member, 'name')))
        self.fields['member_name'].choices = mem
    
    class Meta:
        model = Orders
        fields = ['order_type']
    
    def save(self, commit=True):
        order_prefix = {
            '补运': 'PY',
            '补财库': 'PQK',
            '拜孔子': 'PKZ',
            '安太岁': 'ATS',
            '接财神': 'BCS',
            '拜天狗': 'BTG',
            '拜無鬼': 'BWG',
            '拜天宫': 'BTG'
        }
        cleaned_data = self.cleaned_data 
        order = super(OrderForm, self).save(commit=False)
        order.account = AccountUser.objects.get(member_id=self.cleaned_data['member_id'])       
        order_id = '{}{}'.format(order_prefix[cleaned_data['order_type']],generate_membership())
        while(Orders.objects.filter(order_number=order_id)):
            order_id = '{}{}'.format(order_prefix[cleaned_data['order_type']],generate_membership())
        order.order_number = order_id
        if commit:
            order.save()
            for name in cleaned_data['member_name']:
                order.member.add(Member.objects.get(account__member_id=cleaned_data['member_id'], name=name))
        return order

class AdminForm(OrderForm):
    order_number = forms.CharField(max_length=36)
    status = forms.CharField(max_length=50)

    def __init__(self, request, *args, **kwargs):
        super(AdminForm, self).__init__(request, *args, **kwargs)

    
        

services/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from users.models import Member
from users.utilities import get_current_lunar_date
from .forms import OrderForm, AdminForm
from .filters import OrderFilter
from .models import Orders

from docxtpl import DocxTemplate
import datetime

LUNAR_CONVERSION = {
    1: "初一",
    2: "初二",
    3: "初三",
    4: "初四",
    5: "初五",
    6: "初六",
    7: "初七",
    8: "初八",
    9: "初九",
    10: "初十",
    11: "十一",
    12: "十二",
    13: "十三",
    14: "十四",
    15: "十五",
    16: "十六",
    17: "十七",
    18: "十八",
    19: "十九",
    20: "二十",
    21: "廿一",
    22: "廿二",
    23: "廿三",
    24: "廿四",
    25: "廿五",
    26: "廿六",
    27: "廿七",
    28: "廿八",
    29: "廿九",
    30: "三十",
}   

@login_required
def services(request):
    if request.method == "POST":
        form = OrderForm(request=request, data=request.POST)
        if form.is_valid():
            order = form.save()
            messages.success(request, "Order Submitted!")
        else:
            for key, error in list(form.errors.items()):
                messages.error(request, error)
    else:
        form = OrderForm(request)
    return render(
        request=request,
        template_name = "services/services.html",
        context={"form": form,
            "member_id": request.user.member_id
        }
    )
  
@login_required
def orderSearch(request):
    orders = Orders.objects.all()
    
    myFilter = OrderFilter(request.GET, queryset=orders)
    orders = myFilter.qs
    
    return render(
        request=request,
        template_name = "services/orderSearch.html",
        context={
            "orders": orders,
            "myFilter": myFilter
        }
    )
    

def renderDocument(request):
    if request.method == "POST":
        form = AdminForm(request=request, data=request.POST)
        if form.is_valid():
            current_lunar_date = get_current_lunar_date()    
            if request.POST.get('action') == "preview":
                response = HttpResponse(content_type="application/vnd.openxmlformats-officedocument.wordprocessingml.document")
                if form.cleaned_data.get("order_type") == "安太岁":
                    doc = DocxTemplate('services/templates/docx/antaisui.docx')
                    context = {
                        "unit": request.user.unit_number,
                        "block": request.user.block_number,
                        "name": form.cleaned_data.get('member_name'),
                        "day": LUNAR_CONVERSION[current_lunar_date]
                    }
                    response["Content-Disposition"] = 'filename="ats' + str(datetime.datetime.now()) + '.docx"'
                elif form.cleaned_data.get("order_type") == "拜孔子":
                    doc = DocxTemplate('services/templates/docx/antaisui.docx')
                    context = {
                        "unit": request.user.unit_number,
                        "block": request.user.block_number,
                        "name": form.cleaned_data.get('member_name'),
                        "day": LUNAR_CONVERSION[current_lunar_date]
                    }
                    response["Content-Disposition"] = 'filename="bkz' + str(datetime.datetime.now()) + '.docx"'
                elif form.cleaned_data.get("order_type") == "补财库":
                    doc = DocxTemplate('services/templates/docx/pucaiku.docx')
                    context = {
                        "unit": request.user.unit_number,
                        "block": request.user.block_number,
                        "name": form.cleaned_data.get('member_name'),
                        "day": LUNAR_CONVERSION[current_lunar_date]
                    }
                    
                elif form.cleaned_data.get("order_type") == "补运":
                    doc = DocxTemplate('services/templates/docx/puyun.docx')
                    context = {
                        "unit": request.user.unit_number,
                        "block": request.user.block_number,
                        "name": form.cleaned_data.get('member_name'),
                        "day": LUNAR_CONVERSION[current_lunar_date],
                        "newline": "\n"
                    }
                    response["Content-Disposition"] = 'filename="py' + str(datetime.datetime.now()) + '.docx"'
                doc.render(context)
                doc.save(response)
                
                return response
            else:
                order = Orders.objects.filter(order_number=form.cleaned_data['order_number']).update(status="Completed")
                return redirect('order_search')
                
                
                
    

services/templates/services/orderSearch.html
{% extends "main/base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
<div class="row">
	<div class="col-xs-6 col-xs-offset-3">
		<form method="get">
		{{myFilter.form}}
		<button class="btn btn-primary" type="submit">Search</button>
		</form>
	</div>
</div>
<div class="row">
	<div class="col-xs-6 col-xs-offset-3">
		<div class="content-section">
			<table>
			<tr>
				<th> Order Number</th>
				<th> Member ID</th>
				<th> Name</th>
				<th> Order Type</th>
				<th> Status</th>
			</tr>
			{% if orders %}
			{% for order in orders %}
				<form method="POST" action="{% url 'render_document' %}">
					{% csrf_token %}
					</tr>
						<td>{{order.order_number}}</td>
						<input type="hidden" name="order_number" id="id_order_number" value="{{ order.order_number }}">
						<td>{{order.account.member_id}}</td>
						<input type="hidden" name="member_id" id="id_member_id" value="{{ order.account.member_id }}">
						<td>
						{% for member in order.member.all %}
							<input type="hidden" name="member_name" value="{{ member }}">
							{{member}} </br>
						{% endfor %}
						</td>
						<td>{{order.order_type}}</td>
						<input type="hidden" name="order_type" value="{{ order.order_type }}">
						<td>{{order.status}}</td>
						<input type="hidden" name="status" value="{{ order.status }}">
						<td><button> Print</button></td>
						<td><button class="btn btn-outline-info" name="action" value="preview" type="submit"> Preview</button></td>
						<td><button class="btn btn-outline-info" name="action" value="completed" type="submit"> Completed</button></td>
					</tr>
				</form>
			{% endfor %}
			{% endif %}
			</table>
		</div>
	</div>
</div>
{% endblock %}

services/templates/services/services.html
{% extends "main/base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
<div class="container">
	<div class="row">
		<div class="content-section">
			<form method="POST">
				{% csrf_token %}
					{{form.order_type}}
					<input type="hidden" name="member_id" id="id_member_id" value="{{ member_id }}">
					<label for="id_member_name" class=" requiredField"> Member*</label>
					{% for member in member_profile %}
					<div class="card-group">
						<div class="col-md-4">
						  <div class="card">
							<img class="card-img-top" src="C:\Users\Kezuko\Desktop\WeChat Image_20211106224024.jpg" alt="Card image cap">
							<div class="card-body">
							  <h5 class="card-title">Card title</h5>
							  <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
							  <button href="#" class="btn btn-primary" type="submit">Go somewhere</button>
							</div>
						  </div>
						</div>
						<div class="col-md-4">
						  <div class="card">
							<img class="card-img-top" src="C:\Users\Kezuko\Desktop\WeChat Image_20211106224024.jpg" alt="Card image cap">
							<div class="card-body">
							  <h5 class="card-title">Card title</h5>
							  <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
							  <button href="#" class="btn btn-primary" type="submit">Go somewhere</button>
							</div>
						  </div>
						</div>
						<div class="col-md-4">
						  <div class="card">
							<img class="card-img-top" src="C:\Users\Kezuko\Desktop\WeChat Image_20211106224024.jpg" alt="Card image cap">
							<div class="card-body">
							  <h5 class="card-title">Card title</h5>
							  <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
							  <button href="#" class="btn btn-primary" type="submit">Go somewhere</button>
							</div>
						  </div>
						</div>
						<div class="col-md-4">
						  <div class="card">
							<img class="card-img-top" src="C:\Users\Kezuko\Desktop\WeChat Image_20211106224024.jpg" alt="Card image cap">
							<div class="card-body">
							  <h5 class="card-title">Card title</h5>
							  <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
							  <button href="#" class="btn btn-primary" type="submit">Go somewhere</button>
							</div>
						  </div>
						</div>
						<div class="col-md-4">
						  <div class="card">
							<img class="card-img-top" src="C:\Users\Kezuko\Desktop\WeChat Image_20211106224024.jpg" alt="Card image cap">
							<div class="card-body">
							  <h5 class="card-title">Card title</h5>
							  <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
							  <button href="#" class="btn btn-primary" type="submit">Go somewhere</button>
							</div>
						  </div>
						</div>

					<!--		<select name="member_name" class="select form_control" id="id_member_name" multiple required>
							{% if member_profile %}
							{% for member in member_profile %}
								<option value="{{ member.name }}"> {{member.name}}</option>
							{% endfor %}
							{% endif %}
							</select>-->
					</div>
					{% endfor %}
				
				<!--{% if messages %}
					{% for message in messages %}
						<div class="alert">
						{{ message }}
						</div>
					{% endfor %}
				{% endif %}-->

				
				<!--<div class="form-group">
					<button class="btn btn-outline-info" type="submit">Order Test</button>
				</div>-->
			</form>
		</div>
	</div>
</div>
{% endblock %}

services/templates/services/servicesDescription.html
{% extends "main/base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
<div class="container">
	<div class="row">
		<div class="col-md-6">
			<img src="C:\Users\Kezuko\Desktop\WeChat Image_20211106224024.jpg" width="100%" height="100%">
		</div>
		<div class="col-md-6">
			<p>{service.description}</p>
		</div>
		<div class="col-md-6">
			<form method="POST">
			{% if member_profile %}
			{% for member in member_profile %}
			  <input type="checkbox" id="member1" name="member1" value="member1">
			  <label for="member1"> Member1</label><br>
			  <input type="checkbox" id="member2" name="member2" value="member2">
			  <label for="member2"> Member 2</label><br>
			  <input type="checkbox" id="member3" name="member3" value="member3">
			  <label for="member3"> Member 3</label><br><br>
			{% endfor %}
			{% endif %}
			<input type="submit" value="Submit">
			</form>
		</div>
	</div>
	<button href="#" class="btn btn-primary" type="submit">Submit Order</button>
<div>